name: CI

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build-test-and-deploy:
    name: Build, Test and Deploy
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: "18"
          registry-url: https://npm.pkg.github.com/

      - name: Install dependencies
        run: npm ci
      - name: Build with ViteJS
        run: npm run build
      - name: Setup AWS CLI
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: eu-central-1
      - name: Sync files to S3 bucket
        run: aws s3 sync dist ${{ secrets.S3_BUCKET }} --delete
      - name: Invalidate CloudFront cache
        run: aws cloudfront create-invalidation --distribution-id ${{ secrets.CLOUDFRONT_DISTRIBUTION_ID }} --paths '/*'
